en:
  greeting_message: 
    "Halo, selamat datang. Layanan ini sudah aktif.\n 
    Kamu akan mendapatkan notifikasi setiap ada update data kasus COVID-19 di Indonesia.\n
    Silahkan ketik command `/help` untuk mengetahui fitur lain yg tersedia."
  farewell_message: 
    "Terima kasih, telah menggunakan layanan ini.\n
    Kamu telah berhenti untuk mendapat update."
  subscribe_message:
    "Layanan sudah aktif.\n
    Kamu akan mendapatkan notifikasi setiap ada update data kasus COVID-19 di Indonesia.\n"
  help_message:
    "/update : untuk mendapatkan info jumlah data kasus COVID-19 terbaru.\n
    /subscribe : untuk mendapatkan layanan broadcast info terupdate jumlah data kasus COVID-19.\n
    /unsubs : untuk berhenti dari layanan ini.\n
    /help : jika kamu bingung."
  
  update_message: 
    "Update kasus *COVID-19* pada `**last_update**` di Indonesia:
    \n- Terkonfirmasi : `**infected**`
    \n- Dalam perawatan : `**active**`
    \n- Sembuh : `**recovered**`
    \n- Meninggal : `**death**`
    \nSumber data: **url**"
  unknown_message:
    "Kamu mengirim pesan: `**message_text**`.
    \nMaaf aku tidak mengerti.
    Silahkan ketik '/help' untuk melihat daftar pesan yg bisa aku ngerti."